//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: BootstrapNode.proto

// The protos for exchange bootstrap nodes between region servers.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllBootstrapNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBootstrapNodesRequest) Reset() {
	*x = GetAllBootstrapNodesRequest{}
	mi := &file_BootstrapNode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBootstrapNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBootstrapNodesRequest) ProtoMessage() {}

func (x *GetAllBootstrapNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_BootstrapNode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBootstrapNodesRequest.ProtoReflect.Descriptor instead.
func (*GetAllBootstrapNodesRequest) Descriptor() ([]byte, []int) {
	return file_BootstrapNode_proto_rawDescGZIP(), []int{0}
}

type GetAllBootstrapNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []*ServerName          `protobuf:"bytes,1,rep,name=node" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBootstrapNodesResponse) Reset() {
	*x = GetAllBootstrapNodesResponse{}
	mi := &file_BootstrapNode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBootstrapNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBootstrapNodesResponse) ProtoMessage() {}

func (x *GetAllBootstrapNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_BootstrapNode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBootstrapNodesResponse.ProtoReflect.Descriptor instead.
func (*GetAllBootstrapNodesResponse) Descriptor() ([]byte, []int) {
	return file_BootstrapNode_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllBootstrapNodesResponse) GetNode() []*ServerName {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_BootstrapNode_proto protoreflect.FileDescriptor

var file_BootstrapNode_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x48, 0x42, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x32, 0x71, 0x0a, 0x14, 0x42, 0x6f, 0x6f,
	0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x59, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x57, 0x0a, 0x31,
	0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x13, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x88,
	0x01, 0x01, 0xa0, 0x01, 0x01,
})

var (
	file_BootstrapNode_proto_rawDescOnce sync.Once
	file_BootstrapNode_proto_rawDescData []byte
)

func file_BootstrapNode_proto_rawDescGZIP() []byte {
	file_BootstrapNode_proto_rawDescOnce.Do(func() {
		file_BootstrapNode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BootstrapNode_proto_rawDesc), len(file_BootstrapNode_proto_rawDesc)))
	})
	return file_BootstrapNode_proto_rawDescData
}

var file_BootstrapNode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_BootstrapNode_proto_goTypes = []any{
	(*GetAllBootstrapNodesRequest)(nil),  // 0: pb.GetAllBootstrapNodesRequest
	(*GetAllBootstrapNodesResponse)(nil), // 1: pb.GetAllBootstrapNodesResponse
	(*ServerName)(nil),                   // 2: pb.ServerName
}
var file_BootstrapNode_proto_depIdxs = []int32{
	2, // 0: pb.GetAllBootstrapNodesResponse.node:type_name -> pb.ServerName
	0, // 1: pb.BootstrapNodeService.GetAllBootstrapNodes:input_type -> pb.GetAllBootstrapNodesRequest
	1, // 2: pb.BootstrapNodeService.GetAllBootstrapNodes:output_type -> pb.GetAllBootstrapNodesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_BootstrapNode_proto_init() }
func file_BootstrapNode_proto_init() {
	if File_BootstrapNode_proto != nil {
		return
	}
	file_HBase_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BootstrapNode_proto_rawDesc), len(file_BootstrapNode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_BootstrapNode_proto_goTypes,
		DependencyIndexes: file_BootstrapNode_proto_depIdxs,
		MessageInfos:      file_BootstrapNode_proto_msgTypes,
	}.Build()
	File_BootstrapNode_proto = out.File
	file_BootstrapNode_proto_goTypes = nil
	file_BootstrapNode_proto_depIdxs = nil
}
