//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: IncrementCounterProcessor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncCounterProcessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []byte                 `protobuf:"bytes,1,req,name=row" json:"row,omitempty"`
	Counter       *int32                 `protobuf:"varint,2,req,name=counter" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncCounterProcessorRequest) Reset() {
	*x = IncCounterProcessorRequest{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncCounterProcessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncCounterProcessorRequest) ProtoMessage() {}

func (x *IncCounterProcessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncCounterProcessorRequest.ProtoReflect.Descriptor instead.
func (*IncCounterProcessorRequest) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{0}
}

func (x *IncCounterProcessorRequest) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *IncCounterProcessorRequest) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type IncCounterProcessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *int32                 `protobuf:"varint,1,req,name=response" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncCounterProcessorResponse) Reset() {
	*x = IncCounterProcessorResponse{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncCounterProcessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncCounterProcessorResponse) ProtoMessage() {}

func (x *IncCounterProcessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncCounterProcessorResponse.ProtoReflect.Descriptor instead.
func (*IncCounterProcessorResponse) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{1}
}

func (x *IncCounterProcessorResponse) GetResponse() int32 {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return 0
}

type FriendsOfFriendsProcessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        []byte                 `protobuf:"bytes,1,req,name=person" json:"person,omitempty"`
	Row           []byte                 `protobuf:"bytes,2,req,name=row" json:"row,omitempty"`
	Result        []string               `protobuf:"bytes,3,rep,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendsOfFriendsProcessorRequest) Reset() {
	*x = FriendsOfFriendsProcessorRequest{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendsOfFriendsProcessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsOfFriendsProcessorRequest) ProtoMessage() {}

func (x *FriendsOfFriendsProcessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsOfFriendsProcessorRequest.ProtoReflect.Descriptor instead.
func (*FriendsOfFriendsProcessorRequest) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{2}
}

func (x *FriendsOfFriendsProcessorRequest) GetPerson() []byte {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *FriendsOfFriendsProcessorRequest) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *FriendsOfFriendsProcessorRequest) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

type FriendsOfFriendsProcessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []string               `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendsOfFriendsProcessorResponse) Reset() {
	*x = FriendsOfFriendsProcessorResponse{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendsOfFriendsProcessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsOfFriendsProcessorResponse) ProtoMessage() {}

func (x *FriendsOfFriendsProcessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsOfFriendsProcessorResponse.ProtoReflect.Descriptor instead.
func (*FriendsOfFriendsProcessorResponse) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{3}
}

func (x *FriendsOfFriendsProcessorResponse) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

type RowSwapProcessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row1          []byte                 `protobuf:"bytes,1,req,name=row1" json:"row1,omitempty"`
	Row2          []byte                 `protobuf:"bytes,2,req,name=row2" json:"row2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowSwapProcessorRequest) Reset() {
	*x = RowSwapProcessorRequest{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowSwapProcessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowSwapProcessorRequest) ProtoMessage() {}

func (x *RowSwapProcessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowSwapProcessorRequest.ProtoReflect.Descriptor instead.
func (*RowSwapProcessorRequest) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{4}
}

func (x *RowSwapProcessorRequest) GetRow1() []byte {
	if x != nil {
		return x.Row1
	}
	return nil
}

func (x *RowSwapProcessorRequest) GetRow2() []byte {
	if x != nil {
		return x.Row2
	}
	return nil
}

type RowSwapProcessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowSwapProcessorResponse) Reset() {
	*x = RowSwapProcessorResponse{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowSwapProcessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowSwapProcessorResponse) ProtoMessage() {}

func (x *RowSwapProcessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowSwapProcessorResponse.ProtoReflect.Descriptor instead.
func (*RowSwapProcessorResponse) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{5}
}

type TimeoutProcessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []byte                 `protobuf:"bytes,1,req,name=row" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutProcessorRequest) Reset() {
	*x = TimeoutProcessorRequest{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutProcessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutProcessorRequest) ProtoMessage() {}

func (x *TimeoutProcessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutProcessorRequest.ProtoReflect.Descriptor instead.
func (*TimeoutProcessorRequest) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{6}
}

func (x *TimeoutProcessorRequest) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

type TimeoutProcessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutProcessorResponse) Reset() {
	*x = TimeoutProcessorResponse{}
	mi := &file_IncrementCounterProcessor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutProcessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutProcessorResponse) ProtoMessage() {}

func (x *TimeoutProcessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IncrementCounterProcessor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutProcessorResponse.ProtoReflect.Descriptor instead.
func (*TimeoutProcessorResponse) Descriptor() ([]byte, []int) {
	return file_IncrementCounterProcessor_proto_rawDescGZIP(), []int{7}
}

var File_IncrementCounterProcessor_proto protoreflect.FileDescriptor

var file_IncrementCounterProcessor_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x48, 0x0a, 0x1a, 0x49, 0x6e, 0x63, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22,
	0x39, 0x0a, 0x1b, 0x49, 0x6e, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64, 0x0a, 0x20, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x3b, 0x0a, 0x21, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x66, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x41, 0x0a,
	0x17, 0x52, 0x6f, 0x77, 0x53, 0x77, 0x61, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x31,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x31, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x77, 0x32, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x32,
	0x22, 0x1a, 0x0a, 0x18, 0x52, 0x6f, 0x77, 0x53, 0x77, 0x61, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x17,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x1a, 0x0a, 0x18, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6e, 0x0a, 0x3d, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x63, 0x6f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x23, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x05, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0xa0, 0x01, 0x01,
})

var (
	file_IncrementCounterProcessor_proto_rawDescOnce sync.Once
	file_IncrementCounterProcessor_proto_rawDescData []byte
)

func file_IncrementCounterProcessor_proto_rawDescGZIP() []byte {
	file_IncrementCounterProcessor_proto_rawDescOnce.Do(func() {
		file_IncrementCounterProcessor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_IncrementCounterProcessor_proto_rawDesc), len(file_IncrementCounterProcessor_proto_rawDesc)))
	})
	return file_IncrementCounterProcessor_proto_rawDescData
}

var file_IncrementCounterProcessor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_IncrementCounterProcessor_proto_goTypes = []any{
	(*IncCounterProcessorRequest)(nil),        // 0: pb.IncCounterProcessorRequest
	(*IncCounterProcessorResponse)(nil),       // 1: pb.IncCounterProcessorResponse
	(*FriendsOfFriendsProcessorRequest)(nil),  // 2: pb.FriendsOfFriendsProcessorRequest
	(*FriendsOfFriendsProcessorResponse)(nil), // 3: pb.FriendsOfFriendsProcessorResponse
	(*RowSwapProcessorRequest)(nil),           // 4: pb.RowSwapProcessorRequest
	(*RowSwapProcessorResponse)(nil),          // 5: pb.RowSwapProcessorResponse
	(*TimeoutProcessorRequest)(nil),           // 6: pb.TimeoutProcessorRequest
	(*TimeoutProcessorResponse)(nil),          // 7: pb.TimeoutProcessorResponse
}
var file_IncrementCounterProcessor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IncrementCounterProcessor_proto_init() }
func file_IncrementCounterProcessor_proto_init() {
	if File_IncrementCounterProcessor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_IncrementCounterProcessor_proto_rawDesc), len(file_IncrementCounterProcessor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IncrementCounterProcessor_proto_goTypes,
		DependencyIndexes: file_IncrementCounterProcessor_proto_depIdxs,
		MessageInfos:      file_IncrementCounterProcessor_proto_msgTypes,
	}.Build()
	File_IncrementCounterProcessor_proto = out.File
	file_IncrementCounterProcessor_proto_goTypes = nil
	file_IncrementCounterProcessor_proto_depIdxs = nil
}
