//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Opens a tunnel for remote shell execution on the target server. Used by `CoprocClusterManager`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: ShellExecEndpoint.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShellExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *string                `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	AwaitResponse *bool                  `protobuf:"varint,2,opt,name=await_response,json=awaitResponse" json:"await_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellExecRequest) Reset() {
	*x = ShellExecRequest{}
	mi := &file_ShellExecEndpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExecRequest) ProtoMessage() {}

func (x *ShellExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShellExecEndpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExecRequest.ProtoReflect.Descriptor instead.
func (*ShellExecRequest) Descriptor() ([]byte, []int) {
	return file_ShellExecEndpoint_proto_rawDescGZIP(), []int{0}
}

func (x *ShellExecRequest) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *ShellExecRequest) GetAwaitResponse() bool {
	if x != nil && x.AwaitResponse != nil {
		return *x.AwaitResponse
	}
	return false
}

type ShellExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      *int32                 `protobuf:"varint,1,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	Stdout        *string                `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr        *string                `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellExecResponse) Reset() {
	*x = ShellExecResponse{}
	mi := &file_ShellExecEndpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExecResponse) ProtoMessage() {}

func (x *ShellExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShellExecEndpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExecResponse.ProtoReflect.Descriptor instead.
func (*ShellExecResponse) Descriptor() ([]byte, []int) {
	return file_ShellExecEndpoint_proto_rawDescGZIP(), []int{1}
}

func (x *ShellExecResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ShellExecResponse) GetStdout() string {
	if x != nil && x.Stdout != nil {
		return *x.Stdout
	}
	return ""
}

func (x *ShellExecResponse) GetStderr() string {
	if x != nil && x.Stderr != nil {
		return *x.Stderr
	}
	return ""
}

var File_ShellExecEndpoint_proto protoreflect.FileDescriptor

var file_ShellExecEndpoint_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x53, 0x0a,
	0x10, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61,
	0x77, 0x61, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x77, 0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x60, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x32, 0x4d, 0x0a, 0x10, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x68, 0x65, 0x6c,
	0x6c, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x58, 0x0a, 0x36, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x63,
	0x6f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x11, 0x53,
	0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
})

var (
	file_ShellExecEndpoint_proto_rawDescOnce sync.Once
	file_ShellExecEndpoint_proto_rawDescData []byte
)

func file_ShellExecEndpoint_proto_rawDescGZIP() []byte {
	file_ShellExecEndpoint_proto_rawDescOnce.Do(func() {
		file_ShellExecEndpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ShellExecEndpoint_proto_rawDesc), len(file_ShellExecEndpoint_proto_rawDesc)))
	})
	return file_ShellExecEndpoint_proto_rawDescData
}

var file_ShellExecEndpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ShellExecEndpoint_proto_goTypes = []any{
	(*ShellExecRequest)(nil),  // 0: pb.ShellExecRequest
	(*ShellExecResponse)(nil), // 1: pb.ShellExecResponse
}
var file_ShellExecEndpoint_proto_depIdxs = []int32{
	0, // 0: pb.ShellExecService.shell_exec:input_type -> pb.ShellExecRequest
	1, // 1: pb.ShellExecService.shell_exec:output_type -> pb.ShellExecResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ShellExecEndpoint_proto_init() }
func file_ShellExecEndpoint_proto_init() {
	if File_ShellExecEndpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ShellExecEndpoint_proto_rawDesc), len(file_ShellExecEndpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ShellExecEndpoint_proto_goTypes,
		DependencyIndexes: file_ShellExecEndpoint_proto_depIdxs,
		MessageInfos:      file_ShellExecEndpoint_proto_msgTypes,
	}.Build()
	File_ShellExecEndpoint_proto = out.File
	file_ShellExecEndpoint_proto_goTypes = nil
	file_ShellExecEndpoint_proto_depIdxs = nil
}
