//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: StoreFileTracker.proto

// This file contains protocol buffers that are used for store file tracker.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Size          *uint64                `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileEntry) Reset() {
	*x = StoreFileEntry{}
	mi := &file_StoreFileTracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileEntry) ProtoMessage() {}

func (x *StoreFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_StoreFileTracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileEntry.ProtoReflect.Descriptor instead.
func (*StoreFileEntry) Descriptor() ([]byte, []int) {
	return file_StoreFileTracker_proto_rawDescGZIP(), []int{0}
}

func (x *StoreFileEntry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *StoreFileEntry) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type StoreFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *uint64                `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	StoreFile     []*StoreFileEntry      `protobuf:"bytes,2,rep,name=store_file,json=storeFile" json:"store_file,omitempty"`
	Version       *uint64                `protobuf:"varint,3,opt,name=version,def=1" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for StoreFileList fields.
const (
	Default_StoreFileList_Version = uint64(1)
)

func (x *StoreFileList) Reset() {
	*x = StoreFileList{}
	mi := &file_StoreFileTracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileList) ProtoMessage() {}

func (x *StoreFileList) ProtoReflect() protoreflect.Message {
	mi := &file_StoreFileTracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileList.ProtoReflect.Descriptor instead.
func (*StoreFileList) Descriptor() ([]byte, []int) {
	return file_StoreFileTracker_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFileList) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *StoreFileList) GetStoreFile() []*StoreFileEntry {
	if x != nil {
		return x.StoreFile
	}
	return nil
}

func (x *StoreFileList) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_StoreFileList_Version
}

var File_StoreFileTracker_proto protoreflect.FileDescriptor

var file_StoreFileTracker_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x38, 0x0a, 0x0e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x7d, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01, 0x31, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x5a, 0x0a, 0x31, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x16, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x48, 0x01, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x88, 0x01, 0x01, 0xa0, 0x01,
	0x01,
})

var (
	file_StoreFileTracker_proto_rawDescOnce sync.Once
	file_StoreFileTracker_proto_rawDescData []byte
)

func file_StoreFileTracker_proto_rawDescGZIP() []byte {
	file_StoreFileTracker_proto_rawDescOnce.Do(func() {
		file_StoreFileTracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_StoreFileTracker_proto_rawDesc), len(file_StoreFileTracker_proto_rawDesc)))
	})
	return file_StoreFileTracker_proto_rawDescData
}

var file_StoreFileTracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_StoreFileTracker_proto_goTypes = []any{
	(*StoreFileEntry)(nil), // 0: pb.StoreFileEntry
	(*StoreFileList)(nil),  // 1: pb.StoreFileList
}
var file_StoreFileTracker_proto_depIdxs = []int32{
	0, // 0: pb.StoreFileList.store_file:type_name -> pb.StoreFileEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_StoreFileTracker_proto_init() }
func file_StoreFileTracker_proto_init() {
	if File_StoreFileTracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_StoreFileTracker_proto_rawDesc), len(file_StoreFileTracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StoreFileTracker_proto_goTypes,
		DependencyIndexes: file_StoreFileTracker_proto_depIdxs,
		MessageInfos:      file_StoreFileTracker_proto_msgTypes,
	}.Build()
	File_StoreFileTracker_proto = out.File
	file_StoreFileTracker_proto_goTypes = nil
	file_StoreFileTracker_proto_depIdxs = nil
}
